service: recent-likes

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - package-lock.json
    - package.json
    - venv/**
    - README.md
    - vars.sh
  include:
    - .cache-${env:SPOTIPY_CLIENT_USERNAME}

functions:
  recent-likes:
    handler: update-songs.handler
    events:
        - schedule: cron(0 9 1/1 * ? *)
    environment:
      SPOTIPY_CLIENT_ID: ${env:SPOTIPY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${env:SPOTIPY_CLIENT_SECRET}
      SPOTIPY_REDIRECT_URI: ${env:SPOTIPY_REDIRECT_URI}
      SPOTIPY_CLIENT_USERNAME: ${env:SPOTIPY_CLIENT_USERNAME}
      RECENT_LIKES_PLAYLIST_ID: ${env:RECENT_LIKES_PLAYLIST_ID}
      RECENT_LIKES_PLAYLIST_LEN: ${env:RECENT_LIKES_PLAYLIST_LEN}